URI: https://mze.gov.cz/public/app/wms/plpis_wfs.fcgi
# LPIS WFS layer name with desired polygons.
layer_name: LPIS_DPB_UCINNE
# This list contains settings for LPIS layer where their LandUse code is updated by some value in its attribute.
# base_use_code is the LandUse code for the whole layer, and numbers from values in the controlling attribute are added to base_use_code.
layers:
  - name: "LPIS_layer"
    base_use_code: 10000
    controlling_attribute: "kultura"
    value_increments:
      "chmelnice": 42110 # 52.110
      "jiná kultura": 43110 # 53.110
      "jiná trvalá kultura": 43110 # 53.110
      "mimoprodukční plocha": 51100 # 61.100
      "ovocný sad": 43110 # 53.110
      "plocha s kontejnery": 33300 # 43.300
      "plocha s lanýži": 43110 # 53.110
      "plocha s víceletými produkčními plodinami": 4130 # 14.130 ~ víceleté pícniny, přímé řádky, dobré hydr. podmínky
      "rybník": 62100 # 72.100
      "rychle rostoucí dřeviny": 25000 # 35.000
      "standartní orná půda": 3140  # 13.140 ~ úzkoř. plodiny v přímých řádcích s posklizňovými zbytky ve šp. hydr. podmínkách
      "školka": 24000 # 34.000
      "travní porost (na orné půdě)": 12200 # 22.200
      "trvalý travní porost": 12100 # 22.100
      "úhor": 1110  # 11.110 ~ úhor s posklizňovými zbytky ve šp. hydr. podmínkách
      "vinice": 41110 # 51.110
      "zalesněná půda": 21200 # 31.200

